language: c

dist: trusty
sudo: required

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls cpplint
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

script:
  - ./autogen.sh
  - ./configure
  - make lint
  - make coverage

after_success:
  - coveralls-lcov --repo-token ${COVERALLS_REPO_TOKEN} coverage.info
