language: c

dist: trusty
sudo: required

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls cpplint
  - sudo apt-get install -y lcov

script:
  - ./autogen.sh
  - ./configure
  - make lint
  - make coverage

after_success:
  - coveralls --exclude test --gcov-options '\-lp'
